export const InstaAPI =
  "https://graph.instagram.com/me/media?access_token=IGQVJXWGtBWW9vUHM1QU1HLU5vVVMyRGtHYi1nWG1XclB5blgyYXZAMQlhuTHR1TnNKTHFFVFhyOXJYU2hVaVR0NFNCZAkVYbDR2ckdBcjRPSWV1SVlybThZAWUwya3lGaFlwM2pZAS0lNZAlNVWWlraHZAWVgZDZD&fields=id,caption,media_type,media_url,thumbnail_url,permalink";
